/*
 * Template group createdb.sql
 * Compiled on Sat Oct 03 2015 17:24:50 GMT-0400 (EDT)
 */
var path = require("path");
var base = path.dirname(module.filename);

function getInstance(st, group) {
    "use strict";
var r;
var gFile = "createdb.sql"; 

group.name = "createdb.sql";





//
// Template /createdb
//
r = function(w, rc) {
    var g = this.owningGroup,
        s = this.scope;
    
    w.write("DROP DATABASE IF EXISTS ");
    st.write(w, s, g, rc, st.prop(s, g, rc, s.config, "database", { file: gFile, line: 29, column: 32 }));
    w.write(";");
    w.write("\n");
    w.write("CREATE DATABASE ");
    st.write(w, s, g, rc, st.prop(s, g, rc, s.config, "database", { file: gFile, line: 30, column: 24 }));
    w.write(" CHARACTER SET = utf8;");
    w.write("\n");
    w.write("DROP USER '");
    st.write(w, s, g, rc, st.prop(s, g, rc, s.config, "user", { file: gFile, line: 31, column: 19 }));
    w.write("'@'");
    st.write(w, s, g, rc, st.prop(s, g, rc, s.config, "host", { file: gFile, line: 31, column: 35 }));
    w.write("';");
    w.write("\n");
    w.write("CREATE USER '");
    st.write(w, s, g, rc, st.prop(s, g, rc, s.config, "user", { file: gFile, line: 32, column: 21 }));
    w.write("'@'");
    st.write(w, s, g, rc, st.prop(s, g, rc, s.config, "host", { file: gFile, line: 32, column: 37 }));
    w.write("' IDENTIFIED BY '");
    st.write(w, s, g, rc, st.prop(s, g, rc, s.config, "password", { file: gFile, line: 32, column: 67 }));
    w.write("';");
    w.write("\n");
    w.write("GRANT ALL ON ");
    st.write(w, s, g, rc, st.prop(s, g, rc, s.config, "database", { file: gFile, line: 33, column: 21 }));
    w.write(".* TO ");
    st.write(w, s, g, rc, st.prop(s, g, rc, s.config, "user", { file: gFile, line: 33, column: 44 }));
    w.write(";");
    w.write("\n");
    w.write("USE ");
    st.write(w, s, g, rc, st.prop(s, g, rc, s.config, "database", { file: gFile, line: 34, column: 12 }));
    w.write(";");
    w.write("\n");
    w.write("\n");
    w.write("DROP TABLE IF EXISTS config;");
    w.write("\n");
    w.write("CREATE TABLE config (");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("name VARCHAR(100) PRIMARY KEY,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("nvalue INTEGER,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("tvalue VARCHAR(1000)");
    w.popIndentation();
    w.write("\n");
    w.write(") ENGINE=");
    st.write(w, s, g, rc, st.prop(s, g, rc, s.config, "engine", { file: gFile, line: 41, column: 17 }));
    w.write(" DEFAULT CHARSET=utf8;");
    w.write("\n");
    w.write("\n");
    w.write("-- the schema version");
    w.write("\n");
    w.write("INSERT INTO config VALUES('VersionMajor',0,NULL);");
    w.write("\n");
    w.write("INSERT INTO config VALUES('VersionMinor',1,NULL);");
    w.write("\n");
    w.write("-- default session timeout");
    w.write("\n");
    w.write("INSERT INTO config VALUES('SessionIdleTime',2 * 60 * 60,NULL); -- 2 hr");
    w.write("\n");
    w.write("INSERT INTO config VALUES('SessionMaxTime',8 * 60 * 60,NULL); -- 8 hr");
    w.write("\n");
    w.write("\n");
    w.write("-- name value pairs");
    w.write("\n");
    w.write("-- used to construct select list options");
    w.write("\n");
    w.write("DROP TABLE IF EXISTS nvp;");
    w.write("\n");
    w.write("CREATE TABLE nvp (");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("scope_id INTEGER,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("name VARCHAR(100) NOT NULL,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("val VARCHAR(100) NOT NULL,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("label VARCHAR(100),");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("alias VARCHAR(100),");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("PRIMARY KEY id (scope_id, name, val)");
    w.popIndentation();
    w.write("\n");
    w.write(") ENGINE=");
    st.write(w, s, g, rc, st.prop(s, g, rc, s.config, "engine", { file: gFile, line: 60, column: 17 }));
    w.write(" DEFAULT CHARSET=utf8;");
    w.write("\n");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'CATEGORIES', 'Youth-D', 'Youth-D', 'D');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'CATEGORIES', 'Youth-C', 'Youth-C', 'C');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'CATEGORIES', 'Youth-B', 'Youth-B', 'B');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'CATEGORIES', 'Youth-A', 'Youth-A', 'A');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'CATEGORIES', 'Junior', 'Junior', 'Jr');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'CATEGORIES', 'Adult', 'Adult', NULL);");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'CATEGORIES', 'Open', 'Open', NULL);");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'CATEGORIES', 'Masters', 'Masters', NULL);");
    w.write("\n");
    w.write("-- TODO adult categories are broken down in to Recreational, Intermediate, Advanced");
    w.write("\n");
    w.write("-- need to be able to define rules typically based on age/birth date for membership in category");
    w.write("\n");
    w.write("-- but the rules can also be based on performance. For example from the USAC rules:");
    w.write("\n");
    w.write("-- “For those competitors who register to compete in either Recreational, Intermediate or Advanced, please know that you");
    w.write("\n");
    w.write("-- may attempt any problem at the competitions for your top 5 problems. If, however, you complete 3 or more problems in ");
    w.write("\n");
    w.write("-- the category above the one in which you registered (or 1 problem in two divisions above your registered category) ");
    w.write("\n");
    w.write("-- you will be automatically bumped to the next category.”");
    w.write("\n");
    w.write("\n");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'REGIONS', '101-Puget Sound', '101-Puget Sound', '101');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'REGIONS', '102-Cascadia', '102-Cascadia', '102');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'REGIONS', '201-Northern CA', '201-Northern CA', '201');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'REGIONS', '202-Southern CA', '202-Southern CA', '202');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'REGIONS', '301-Mountain West', '301-Mountain West', '301');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'REGIONS', '302-Front Range', '302-Front Range', '302');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'REGIONS', '401-The Desert', '401-The Desert', '401');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'REGIONS', '402-South Central', '402-South Central', '402');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'REGIONS', '501-Midwest', '501-Midwest', '501');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'REGIONS', '502-Great Lakes', '502-Great Lakes', '502');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'REGIONS', '601-Southeast', '601-Southeast', '601');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'REGIONS', '602-Midsouth', '602-Midsouth', '602');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'REGIONS', '701-Capital', '701-Capital', '701');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'REGIONS', '702-Rustbelt', '702-Rustbelt', '702');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'REGIONS', '801-New England West', '801-New England West', '801');");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'REGIONS', '802-New England East', '802-New England East', '802');");
    w.write("\n");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'SERIES', 'SCS', 'SCS', NULL);");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'SERIES', 'ABS', 'ABS', NULL);");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'SERIES', 'CCS', 'CCS', NULL);");
    w.write("\n");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'SANCTIONING', 'Local', 'Local', NULL);");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'SANCTIONING', 'Regional', 'Regional', NULL);");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'SANCTIONING', 'Divisional', 'Divisional', NULL);");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'SANCTIONING', 'National', 'National', NULL);");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'SANCTIONING', 'None', 'None', NULL);");
    w.write("\n");
    w.write("\n");
    w.write("INSERT INTO nvp VALUES(-1, 'EVENT_TYPE', 'Red Point', 'Red Point', NULL);");
    w.write("\n");
    w.write("-- todo other types such as On Sight, Speed etc.");
    w.write("\n");
    w.write("-- USAC rules call these formats: On Sight, Flash, Redpoint, Redpoint modified");
    w.write("\n");
    w.write("-- A comp may have multiple rounds and they can be of different formats. ");
    w.write("\n");
    w.write("-- The heist even mixes bouldering and lead climbing ");
    w.write("\n");
    w.write("\n");
    w.write("\n");
    w.write("DROP TABLE IF EXISTS event;");
    w.write("\n");
    w.write("CREATE TABLE event (");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("version INTEGER DEFAULT 1,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("region VARCHAR(100), -- REGIONS");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("location VARCHAR(200) NOT NULL, -- Example 'Boston Rock Gym'");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("event_date DATE NOT NULL,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("series VARCHAR(100), -- SERIES");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("sanctioning VARCHAR(100) NOT NULL, -- SANCTIONING");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("type VARCHAR(100) NOT NULL, -- EVENT_TYPE");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("state ENUM('Open', 'Active', 'Preliminary', 'Closed'),");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("bib_number_digits INTEGER(1) NOT NULL DEFAULT 3,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("record_falls_per_climb BOOLEAN NOT NULL,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("routes_have_location BOOLEAN NOT NULL,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("routes_have_color BOOLEAN NOT NULL,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("-- xxx for redpoint need to configure the number of routes to consider for top score ABS defaults to 5 SCS defaults to 3");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("-- todo something to select/define the scoring/ranking system or is this tied to type");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("score_card_columns INTEGER DEFAULT 2,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("notes VARCHAR(1000),");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("updated_by VARCHAR(100),");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP");
    w.popIndentation();
    w.write("\n");
    w.write(") ENGINE=");
    st.write(w, s, g, rc, st.prop(s, g, rc, s.config, "engine", { file: gFile, line: 134, column: 17 }));
    w.write(" DEFAULT CHARSET=utf8;");
    w.write("\n");
    w.write("\n");
    w.write("CREATE TRIGGER event_update");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("BEFORE UPDATE ON event");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("FOR EACH ROW");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("set NEW.version = NEW.version + 1;");
    w.popIndentation();
    w.write("\n");
    w.write("\n");
    w.write("DROP TABLE IF EXISTS climber;");
    w.write("\n");
    w.write("CREATE TABLE climber (");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("version INTEGER DEFAULT 1,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("usac_member_id INTEGER,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("first_name VARCHAR(100),");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("last_name VARCHAR(100) NOT NULL,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("gender ENUM('Male', 'Female'),");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("category VARCHAR(100), -- CATEGORIES");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("birth_date DATE,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("region VARCHAR(100), -- REGIONS");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("team VARCHAR(100),");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("coach VARCHAR(100),");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("-- TODO consider other things like phone number, email, location, has waver, Citizen, possibly general purpose columns");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("updated_by VARCHAR(100),");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,");
    w.popIndentation();
    w.write("\n");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("UNIQUE INDEX usac_member_id_ndx (usac_member_id),");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("INDEX name_ndx (first_name, last_name)");
    w.popIndentation();
    w.write("\n");
    w.write(") ENGINE=");
    st.write(w, s, g, rc, st.prop(s, g, rc, s.config, "engine", { file: gFile, line: 160, column: 17 }));
    w.write(" DEFAULT CHARSET=utf8;");
    w.write("\n");
    w.write("\n");
    w.write("CREATE TRIGGER climber_update");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("BEFORE UPDATE ON climber");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("FOR EACH ROW");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("set NEW.version = NEW.version + 1;");
    w.popIndentation();
    w.write("\n");
    w.write("\n");
    w.write("DROP TABLE IF EXISTS event_route;");
    w.write("\n");
    w.write("CREATE TABLE event_route (");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("number INTEGER(3) NOT NULL, -- to consider that for non read-point comps routes are designated like Q1, Q2..., SF1..., F1, F2... and are also specific to a category e.g. FYDQ1");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("event_id INTEGER NOT NULL,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("color VARCHAR(20),");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("location VARCHAR(20),");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("points INTEGER NOT NULL, -- This is the points for a top");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("-- based on the points the route is associated with a category for the purpose of adult sub category assignment");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("-- or for a modified red point comp you can have different colored score cards so that competitors in a given category can only climb routes matching that category");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("-- time limit typically the same for all routes but the rules allow each route to have its own time limit");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("sheet_row INTEGER,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("sheet_column INTEGER,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("-- for onsight/flash each hold has a point value and there are some other things like bridges etc. There is also a picture of the route.");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("PRIMARY KEY id (number, event_id)");
    w.popIndentation();
    w.write("\n");
    w.write(") ENGINE=");
    st.write(w, s, g, rc, st.prop(s, g, rc, s.config, "engine", { file: gFile, line: 181, column: 17 }));
    w.write(" DEFAULT CHARSET=utf8;");
    w.write("\n");
    w.write("\n");
    w.write("DROP TABLE IF EXISTS event_climber;");
    w.write("\n");
    w.write("CREATE TABLE event_climber (");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("climber_id INTEGER NOT NULL,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("event_id INTEGER NOT NULL,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("bib_number INTEGER(4) NOT NULL, -- xxx usac bib number starts with F or M and then 4 digits can have F1010 and M1010");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("-- for adults they can enter a different category for the event subject to some age requirements");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("-- the adult category has flexible sub divisions: Recreational, Intermediate or Advanced");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("-- also other kinds of comps may define categories differently but there could still be value in using the master climber list");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("category VARCHAR(100), -- event category. CATEGORIES or event specific categories");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("-- score card category could be different from category typically assigned based on rules(category)");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("region VARCHAR(100), -- region at time of event");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("team VARCHAR(100), -- team at time of event");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("coach VARCHAR(100), -- coach at time of event");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("version INTEGER DEFAULT 1,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("start_order INTEGER, -- for ");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("total INTEGER, -- xxx is this before or after total_falls is subtracted??? either way it too could be calculated");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("place INTEGER, -- xxx this will be generated, rename to rank?");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("top1 INTEGER,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("top2 INTEGER,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("top3 INTEGER,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("top4 INTEGER,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("top5 INTEGER,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("total_falls INTEGER,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("time_taken INTEGER, -- xxx what type to use for delta time?  speed is recorded to two decimal places e.g.14.45 seconds");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("climbs VARCHAR(6000), -- data for the client use only");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("updated_by VARCHAR(100),");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("scored_by VARCHAR(100),");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("scored_on TIMESTAMP NULL DEFAULT NULL,");
    w.popIndentation();
    w.write("\n");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("PRIMARY KEY id (climber_id, event_id),");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("UNIQUE INDEX event_number (bib_number, event_id)");
    w.popIndentation();
    w.write("\n");
    w.write(") ENGINE=");
    st.write(w, s, g, rc, st.prop(s, g, rc, s.config, "engine", { file: gFile, line: 215, column: 17 }));
    w.write(" DEFAULT CHARSET=utf8;");
    w.write("\n");
    w.write("\n");
    w.write("CREATE TRIGGER event_climber_update");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("BEFORE UPDATE ON event_climber");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("FOR EACH ROW");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("set NEW.version = NEW.version + 1;");
    w.popIndentation();
    w.write("\n");
    w.write("\n");
    w.write("-- users and sessions");
    w.write("\n");
    w.write("DROP TABLE IF EXISTS app_user;");
    w.write("\n");
    w.write("CREATE TABLE `app_user` (");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("version INTEGER DEFAULT 1,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("username VARCHAR(100) NOT NULL, -- name of user (required and non empty)");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("pwd_hash VARCHAR(100) NOT NULL, -- one way encrypted value of password");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("role ENUM('Reader', 'Contributor', 'Admin') NOT NULL,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("first_name VARCHAR(100),");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("last_name VARCHAR(100),");
    w.popIndentation();
    w.write("\n");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("UNIQUE INDEX username_idx (username)");
    w.popIndentation();
    w.write("\n");
    w.write(") ENGINE=");
    st.write(w, s, g, rc, st.prop(s, g, rc, s.config, "engine", { file: gFile, line: 234, column: 17 }));
    w.write(" DEFAULT CHARSET=utf8;");
    w.write("\n");
    w.write("\n");
    w.write("CREATE TRIGGER app_user_update");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("BEFORE UPDATE ON app_user");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("FOR EACH ROW");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("      ");
    w.write("set NEW.version = NEW.version + 1;");
    w.popIndentation();
    w.write("\n");
    w.write("\n");
    w.write("-- Must have an initial default admin user");
    w.write("\n");
    w.write("INSERT INTO app_user (username, pwd_hash, role) VALUES ('admin', password('admin'), 'Admin');");
    w.write("\n");
    w.write("\n");
    w.write("DROP TABLE IF EXISTS app_session;");
    w.write("\n");
    w.write("CREATE TABLE `app_session` (");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("session_id VARCHAR(256) NOT NULL,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("accessed_on TIMESTAMP NULL DEFAULT NULL,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("username VARCHAR(100) NOT NULL,");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("  ");
    w.write("role ENUM('Reader', 'Contributor', 'Admin') NOT NULL,");
    w.popIndentation();
    w.write("\n");
    w.write("\n");
    w.pushIndentation("  ");
    w.write("UNIQUE INDEX session_idx (session_id)");
    w.popIndentation();
    w.write("\n");
    w.write(") ENGINE=");
    st.write(w, s, g, rc, st.prop(s, g, rc, s.config, "engine", { file: gFile, line: 254, column: 17 }));
    w.write(" DEFAULT CHARSET=utf8;");
    w.write("\n");
};
r.args = [
        { name: "config"     }
];
group.addTemplate("/createdb", r); 


return group;
}
getInstance.base = base;

module.exports = getInstance;